<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ArquivosGravacao\**" />
    <EmbeddedResource Remove="ArquivosGravacao\**" />
    <None Remove="ArquivosGravacao\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="NewFile1.txt" />
  </ItemGroup>

</Project>